### ISSUE TITLE
[BUG] Build fails with ESPHome 2026.2.0: esp_spiffs.h: No such file or directory

### ISSUE THREAD

**Issue by salmon-21** [francescopace/pisense#85]
## Description

ESPectre fails to compile on ESPHome 2026.2.0 with `fatal error: esp_spiffs.h: No such file or directory`.

ESPHome 2026.2.0 introduced selective ESP-IDF component compilation ([#13610](https://github.com/esphome/esphome/pull/13610), [#13664](https://github.com/esphome/esphome/pull/13664)), which excludes unused ESP-IDF components at build time. Since `spiffs` is not declared as a dependency by the ESPectre component, it is now excluded from the build, causing `calibration_file_buffer.cpp` to fail.

## Steps to Reproduce

1. Install ESPHome 2026.2.0 (e.g., via Home Assistant ESPHome Device Builder add-on)
2. Use `examples/espectre-s3.yaml` (or any other example config)
3. Compile

## Expected Behavior

Build succeeds.

## Actual Behavior

Build fails with:

```
calibration_file_buffer.cpp:13:10: fatal error: esp_spiffs.h: No such file or directory
   13 | #include "esp_spiffs.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

## Environment

- **ESP32 Model**: ESP32-S3 (likely affects all variants)
- **ESPectre Version/Commit**: v2.5.0 / main branch
- **Platform**: ESPHome
- **ESPHome Version**: 2026.2.0

## Configuration

```yaml
# examples/espectre-s3.yaml (unmodified)
```

## Root Cause

`calibration_file_buffer.cpp` includes `esp_spiffs.h`, but the ESPectre component's `__init__.py` does not call `include_builtin_idf_component("spiffs")`. In ESPHome ≤2026.1.x, all ESP-IDF components were compiled regardless. In 2026.2.0, unused components are excluded, so `spiffs` must be explicitly re-enabled.

## Suggested Fix

In `components/espectre/__init__.py`:

1. Add `include_builtin_idf_component` to the import:

```python
from esphome.components.esp32 import add_extra_build_file, add_idf_sdkconfig_option, include_builtin_idf_component
```

2. Call it in `to_code()`:

```python
    # Re-enable the spiffs ESP-IDF component (excluded by ESPHome by default since 2026.2.0)
    # Required because calibration_file_buffer.cpp includes esp_spiffs.h
    include_builtin_idf_component("spiffs")
```

## Additional Context

- CI (release.yml) uses `pip install esphome` which installed 2026.1.5 at the time of the v2.5.0 release, so the build succeeded.
- This will also affect CI once it picks up ESPHome ≥2026.2.0.

**Comment by francescopace** [comment]
Thanks for the detailed bug report @salmon-21!

The fix has been merged and is now available on the `develop` branch. 
Feel free to test it and provide feedback.

We explicitly include the SPIFFS component using `include_builtin_idf_component("spiffs")`, and the fix is backward compatible with older ESPHome versions.

Thanks @fulviodannibale for the PR #87
